const blogData = [
    [
        {
            id: 1,
            imageUrl: "https://demo2.themelexus.com/farmor/wp-content/uploads/2023/09/blog-4-450x330.jpg",
            date: "September 12, 2023",
            author: "Admin",
            comments: 5,
            title: "Fresh Vegetable Food",
            link: "https://example.com/blog/fresh-vegetable-food",
          },
          {
            id: 2,
            imageUrl: "https://demo2.themelexus.com/farmor/wp-content/uploads/2023/09/blog-3-450x330.jpg",
            date: "September 10, 2023",
            author: "Admin",
            comments: 8,
            title: "Healthy Recipes",
            link: "https://example.com/blog/healthy-recipes",
          },
          {
            id: 3,
            imageUrl: "https://demo2.themelexus.com/farmor/wp-content/uploads/2023/09/blog-2-450x330.jpg",
            date: "September 8, 2023",
            author: "Admin",
            comments: 12,
            title: "Organic Farming Benefits",
            link: "https://example.com/blog/organic-farming-benefits",
          },
          {
            id: 4,
            imageUrl: "https://demo2.themelexus.com/farmor/wp-content/uploads/2023/09/blog-1-450x330.jpg",
            date: "September 5, 2023",
            author: "Admin",
            comments: 6,
            title: "Cooking Tips for Beginners",
            link: "https://example.com/blog/cooking-tips",
          },
          {
            id: 5,
            imageUrl: "https://demo2.themelexus.com/farmor/wp-content/uploads/2023/08/blog-5-450x330.jpg",
            date: "August 30, 2023",
            author: "Admin",
            comments: 10,
            title: "Delicious Summer Desserts",
            link: "https://example.com/blog/summer-desserts",
          },
          {
            id: 6,
            imageUrl: "https://demo2.themelexus.com/farmor/wp-content/uploads/2023/08/blog-6-450x330.jpg",
            date: "August 28, 2023",
            author: "Admin",
            comments: 7,
            title: "The Art of Plating",
            link: "https://example.com/blog/art-of-plating",
          },
          {
            id: 7,
            imageUrl: "https://demo2.themelexus.com/farmor/wp-content/uploads/2023/08/blog-7-450x330.jpg",
            date: "August 25, 2023",
            author: "Admin",
            comments: 9,
            title: "Farm-to-Table Movement",
            link: "https://example.com/blog/farm-to-table",
          },
          {
            id: 8,
            imageUrl: "https://demo2.themelexus.com/farmor/wp-content/uploads/2023/08/blog-8-450x330.jpg",
            date: "August 20, 2023",
            author: "Admin",
            comments: 4,
            title: "Seasonal Cooking Tips",
            link: "https://example.com/blog/seasonal-cooking-tips",
          },
          {
            id: 9,
            imageUrl: "https://demo2.themelexus.com/farmor/wp-content/uploads/2023/08/blog-9-450x330.jpg",
            date: "August 18, 2023",
            author: "Admin",
            comments: 11,
            title: "Gardening Essentials",
            link: "https://example.com/blog/gardening-essentials",
          },
    ],
    [
        {
            id: 10,
            imageUrl: "https://demo2.themelexus.com/farmor/wp-content/uploads/2023/08/blog-10-450x330.jpg",
            date: "August 15, 2023",
            author: "Admin",
            comments: 6,
            title: "Tips for Preserving Fresh Produce",
            link: "https://example.com/blog/preserving-fresh-produce",
          },
          {
            id: 11,
            imageUrl: "https://demo2.themelexus.com/farmor/wp-content/uploads/2023/08/blog-11-450x330.jpg",
            date: "August 12, 2023",
            author: "Admin",
            comments: 8,
            title: "Homemade Snack Ideas",
            link: "https://example.com/blog/homemade-snack-ideas",
          },
          {
            id: 12,
            imageUrl: "https://demo2.themelexus.com/farmor/wp-content/uploads/2023/08/blog-12-450x330.jpg",
            date: "August 10, 2023",
            author: "Admin",
            comments: 7,
            title: "Exploring Culinary Herbs",
            link: "https://example.com/blog/culinary-herbs",
          },
          {
            id: 13,
            imageUrl: "https://demo2.themelexus.com/farmor/wp-content/uploads/2023/08/blog-13-450x330.jpg",
            date: "August 8, 2023",
            author: "Admin",
            comments: 9,
            title: "Weekend Cooking Adventures",
            link: "https://example.com/blog/cooking-adventures",
          },
          {
            id: 14,
            imageUrl: "https://demo2.themelexus.com/farmor/wp-content/uploads/2023/08/blog-14-450x330.jpg",
            date: "August 5, 2023",
            author: "Admin",
            comments: 5,
            title: "Family-Friendly Meals",
            link: "https://example.com/blog/family-friendly-meals",
          },
          {
            id: 15,
            imageUrl: "https://demo2.themelexus.com/farmor/wp-content/uploads/2023/08/blog-15-450x330.jpg",
            date: "August 2, 2023",
            author: "Admin",
            comments: 10,
            title: "Healthy Lunch Ideas",
            link: "https://example.com/blog/healthy-lunch-ideas",
          },
    ]
    
   
  ];
  
  export default blogData;
  