export const imageUrls = [
    "/products/ce.png",
    "/products/fbr.png",
    "/products/fda.png",
    "/products/fssc.png",
    "/products/mdr.png",
    "/products/sbp.png",
    "/products/sgs.png",
    "/products/psw.jpeg",
    "/products/gmp.jpeg",
    "/products/haccp.jpeg",
    "/products/secp.jpeg",
    "/products/tadp.jpeg",
    "/products/cornimg (1).jpeg",
    // "https://demo2.themelexus.com/farmor/wp-content/uploads/2023/09/brand02.svg",
    // "https://demo2.themelexus.com/farmor/wp-content/uploads/2023/09/brand03.svg",
    // "https://demo2.themelexus.com/farmor/wp-content/uploads/2023/09/brand04.svg",
    // "https://demo2.themelexus.com/farmor/wp-content/uploads/2023/09/brand05.svg",
    // "https://demo2.themelexus.com/farmor/wp-content/uploads/2023/09/brand06.svg",
    // "https://demo2.themelexus.com/farmor/wp-content/uploads/2023/09/brand03.svg",
  ];